### ISSUE TITLE
Asclin test

### ISSUE THREAD

**Issue by kdy008521** [realsosy/InfineonRacer#43]
Asclin 모듈의 경우 iLLD만 존재하고 test file이 없어 새로 만들어야 하는 어려움이 있습니다.

iLLD의 Asc 함수들을 보면 input으로 *asclin과 *config를 받는데 이곳에 무엇을 입력해야 할지 잘 모르겠습니다.

조언 부탁 드립니다.

**Comment by wootaik** [comment]
* Asclin을 Shell 에서 호출하여 사용하는 구조로 되어 있어서 별도의 test 는 진행하지 않았습니다.

* iLLD 함수들에 대한 활용 방법에 대한 설명은 3. What is iLLD 부분을 살펴보도록 하세요. iLLD가 초보자에게 어려워 보일 수 있습니다만, 활용법을 익히시면 사용하기 좋습니다.

* 그리고 이곳은 게시판이 아니라 프로젝트 진행과 버드들을 관리하는 곳입니다.  앞으로는 대회 게시판을 활용해 주세요.
