### ISSUE TITLE
Synchronized PWM

### ISSUE THREAD

**Issue by whdgks23** [realsosy/InfineonRacer#47]
H - Bridge 를 이용하여 모터 두개를 구동시키는데, tc에서 저희가 입력해주는 전압이 각각 같은 경우에 모터의 회전속도가 다르게 나타납니다. 
Connection Guide 를 읽어보니, 모터 두개를 사용하기 위해서는 납땜을 해야한다고 나와있는데, 위와 같은 문제가 발생하는 원인이 납땜을 하지 않았기 때문일까요~?

**Comment by wootaik** [comment]
두번째 모터는 핀을 변경해야 합니다. Connection Guide 참고하세요.
이곳은 문의 게시판이 아닙니다.  문의는 대회 게시판을 이용해 주세요.
